inherit_gem:
  rubocop-inst:
  - rubocop.yml
  - rubocop-rspec.yml

require:
  - rubocop-rake

AllCops:
  TargetRubyVersion: 2.5

# ModBus's master/slave terminology can be updated, but not now
Naming/InclusiveLanguage:
  Enabled: false

RSpec/BeforeAfterAll:
  Enabled: false
RSpec/SpecFilePathFormat:
  Exclude:
   - spec/ext_spec.rb
   - spec/mod_bus/proxy_spec.rb
   - spec/mod_bus/read_rtu_response_spec.rb
   - spec/mod_bus/rtu_via_tcp_client_spec.rb
RSpec/InstanceVariable:
  Enabled: false

Style/BlockDelimiters:
  AllowedMethods: []
Style/DocumentDynamicEvalDefinition:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/DoubleNegation:
  Enabled: false
Style/ParallelAssignment:
  Enabled: false
